### ISSUE TITLE
Incompatable with Blockus 1.18.2 (fabric)

### ISSUE THREAD

**Issue by Alec153** [coolsimulations/SurvivalPlus#10]
Crash on launch when blockus version 2.4.0+1.18.2 is installed. Fabric/API versions latest. SurvivalPlus version 1.18.2-0.1.6c
[crash-2022-03-18_17.30.14-server.txt](https://github.com/coolsimulations/SurvivalPlus/files/8307958/crash-2022-03-18_17.30.14-server.txt)

**Comment by coolsimulations** [comment]
Thanks! I thought I was being all super cool and sneaky by supporting 1.18.2 Blockus before it was even out.... turns out I forget a single line of code XD Anyway, all fixed with this https://github.com/coolsimulations/SurvivalPlus/commit/06abb18d241f226c3e3a495c4304fb955835a9e3 and SurvivalPlus 0.1.6d is now available for download.
