### ISSUE TITLE
Cheese in crafting slot after creating items (1.18.2 Fabric)

### ISSUE THREAD

**Issue by DatrixTHLK** [coolsimulations/SurvivalPlus#12]
Hi there,

I seem to get cheese as a crafting material even though I have nothing to craft it in the first place. It's not the 9 slot crafting materials area it's the 1x1 results area that it shows up in.

Minecraft 1.18.2
Fabric: 0.13.3
SurvivalPlus: 0.1.64

**Comment by coolsimulations** [comment]
Thanks, I’ve been aware of this issue since I release my 1.18.2 update. I recommend opening this as an issue to the [Fabric API repository](https://github.com/FabricMC/fabric).

I believe this is an issue with Fabric itself, rather than SurvivalPlus. As it only occurs on 1.18.2 (not 1.18.1) and only on Fabric. The Forge version of SurvivalPlus doesn’t have this issue.

The reason for it is that I have a [recipe to make cheese](https://github.com/coolsimulations/SurvivalPlus/blob/1.18.x-fabric/src/main/resources/data/survivalplus/recipes/cheese_skyroot.json) from the milk bucket tag from The Aether (Paradise Lost) but since you don’t have that mod it loads an empty recipe (which it shouldn’t). If I remove this cheese recipe, then it reverts to an empty [tin ingot recipe](https://github.com/coolsimulations/SurvivalPlus/blob/1.18.x-fabric/src/main/resources/data/survivalplus/recipes/modernindustrialization/tin_nuggets.json) (which was support to turn tin nuggets into a tin ingot). As if you play with MoreThanAPickaxe, it’s not cheese but instead a [steel adze](https://github.com/coolsimulations/MoreThanAPickaxe/blob/1.18.x-fabric/src/main/resources/data/morethanapickaxe/recipes/steel_adze.json). All because of “empty” tags.

**Comment by DatrixTHLK** [comment]
Hmmm...I see. I'll put this up on to the fabric Github page. Thanks for the help and info for that.

**Comment by DatrixTHLK** [comment]
Actually Fabric updated a day after I opened this issue here and it seems to have fixed the issue.

**Comment by coolsimulations** [comment]
Fixed this issue by using Fabric's new Recipe Conditions https://github.com/coolsimulations/SurvivalPlus/commit/eec66342b4ce002c48e9aaa43e2786da7b3fa629. Will release the update when 1.19 drops
