### ISSUE TITLE
1.19.2 SurvivalPlus crash with Bamboo Everything

### ISSUE THREAD

**Issue by Dravitz** [coolsimulations/SurvivalPlus#18]
Fresh install with only survival plus and bamboo everything with its dependencies.
This took ages to find the one uncommon mod that i added to break my personal modpack.

[crash-2023-02-21_17.18.07-client.txt](https://github.com/coolsimulations/SurvivalPlus/files/10798608/crash-2023-02-21_17.18.07-client.txt)

**Comment by Dravitz** [comment]
[latest.log](https://github.com/coolsimulations/SurvivalPlus/files/10798748/latest.log)

It looks like it is caused by a set of bamboo armor in the output logs above.

**Comment by coolsimulations** [comment]
Tried reproducing [this issue](https://github.com/nanite/Bamboo-Everything/issues/49). Get the same warnings in the log, but what follows is different:
```[modloading-worker-0/WARN]: Registry minecraft:item: Override did not have an associated owner object. Name: survivalplus:bamboo_helmet Value: air
[modloading-worker-0/WARN]: Registry minecraft:item: Override did not have an associated owner object. Name: survivalplus:bamboo_chestplate Value: air
[modloading-worker-0/WARN]: Registry minecraft:item: Override did not have an associated owner object. Name: survivalplus:bamboo_leggings Value: air
[modloading-worker-0/WARN]: Registry minecraft:item: Override did not have an associated owner object. Name: survivalplus:bamboo_boots Value: air
``` 
[2023-02-25-3.log](https://github.com/coolsimulations/SurvivalPlus/files/10830028/2023-02-25-3.log)

The crash report I get is different too. [crash-2023-02-25_11.31.49-client.txt](https://github.com/coolsimulations/SurvivalPlus/files/10830017/crash-2023-02-25_11.31.49-client.txt)

This only happens when both SurvivalPlus and Bamboo Everything is loaded on 1.19.2. I don't know what is causing this, as the code on 1.19.3 is identical on my end, and I can't reproduce the issue on that version. The way I register my bamboo armour is the same as armour from mods like Biomes O' Plenty and that works. I no longer support 1.19.2 anymore, but I would have liked to find out what caused this.
