### ISSUE TITLE
SurvivalPlus only supports JER 0.10.1

### ISSUE THREAD

**Issue by Pengu-Hunter** [coolsimulations/SurvivalPlus#6]
This happens on 1.16.5 I can't find a 0.10.1 version of JustEnoughResources for 1.16.5 so I'm confused as to either where to find this mysterious version of JER or if I've done something wrong.
The forge version is 36.1.16.
The SurvivalPlus version is 0.1.4d.

**Comment by coolsimulations** [comment]
Thanks for the report! It’s because of the new forge version that just came out, Until I release an update in about 2 weeks time I’d recommend downgrading forge to 1.16.5-36.1.9 which will fix all of those mod problems. I’d update sooner but I have no time right now. If you want to fix it yourself it’s just a simple change of the mods.toml file.
